ProductionManageSys/ProductionManage/Controllers/LoginController.cs
using Common;
using Service.IService;
using Service.ServiceImp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionManage.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public IUserInfoManage UserInfoBz = new UserInfoManage();

        [AllowAnonymous]
        public ActionResult Index()
        {
            var userInfo = UserInfoBz.GetAccountCookie();
            return View(userInfo);
        }

        [AllowAnonymous]
        public ActionResult Login(string UserName, string Pwd, bool remember)
        {
            var userInfo = UserInfoBz.UserLogin(UserName, Pwd);
            if (userInfo == null)
                return Json(new { isSuccess = false, Msg = "账号或密码错误！" });
            if (remember) UserInfoBz.SetAccountCookie(userInfo);
            else UserInfoBz.ClearAccountCookie();
            SessionHelper.SetSession("CurUser", userInfo);
            return Json(new { isSuccess = true, Msg = "登录成功！" });
        }

        [AllowAnonymous]
        public ActionResult LoginOut()
        {
            SessionHelper.Del("CurUser");
            UserInfoBz.ClearAccountCookie();
            return RedirectToAction("Index");
        }
    }
}

ProductionManageSys/ProductionManage/Controllers/UserController.cs
using Common;
using Domain.Model;
using Service.IService;
using Service.ServiceImp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionManage.Controllers
{
    public class UserController : BaseController
    {
       
        private IRoleInfoManage RoleInfoManageBz = new RoleInfoManage();
        // GET: BackStage/User
        public ActionResult UserConfig(string msg="")
        {
            var model = UserInfoBz.Get(o => o.ID == CurrentUser.ID);
            ViewBag.selectList = GetSelectList();
            ViewBag.Msg = msg;
            return View(model);
        }

        public IEnumerable<SelectListItem> GetSelectList()
        {
            var selectList = RoleInfoManageBz.LoadAll(o=>true).Select(a => new SelectListItem
            {
                Text = a.RoleName,
                Value = a.ID.ToString()
            }).ToList();
            selectList.Insert(0, new SelectListItem
            {
                Text = "请选择",
                Value = "0"
            });
            return selectList;
        }
    
        public ActionResult SaveUserConfig(UserInfo entity)
        {
            var userInfo = UserInfoBz.Get(o => o.ID == entity.ID);
            userInfo.UserName = entity.UserName;
            userInfo.IsValid = entity.IsValid;
            userInfo.IsSuperAdmin = entity.IsSuperAdmin;
            userInfo.HeadImgUrl = entity.HeadImgUrl;
            userInfo.RoleID = entity.RoleID;
            var isSuccess = UserInfoBz.Update(userInfo);
            if (isSuccess)
                ViewBag.Msg = "保存成功！";
            else
                ViewBag.Msg = "保存失败！";
            return RedirectToAction("UserConfig",new { msg= ViewBag.Msg });
        }
        //用户管理  
        public ActionResult UserManageIndex(int p = 1, string searchFild = "")
        {
            var model = UserInfoBz.Query(
                             UserInfoBz.LoadAll(o => o.UserName.Contains(searchFild)).OrderByDescending(o => o.ID),
                             p,
                             10);
            ViewBag.searchFild = searchFild;
            var role = RoleInfoManageBz.LoadAll(o => true);
           
            ViewBag.role = role;
            return View(model);
        }
        public ActionResult UserDel(int id)
        {
            var isSuccess = UserInfoBz.Delete(o => o.ID == id);
            if (isSuccess)
            {
                TempData["Msg"] = "删除成功！";
            }
            else
            {
                TempData["Msg"] = "删除失败！";
            }
            return RedirectToAction("UserManageIndex");
        }
        public ActionResult UserEidt(int id = 0)
        {
            var model = UserInfoBz.Get(o => o.ID == id);
            ViewBag.selectList = GetSelectList();
            return View(model);
        }
        [ValidateInput(false)]
        public ActionResult UserSave(UserInfo entity)
        {
            ViewBag.selectList = GetSelectList();
            var ValidUser = UserInfoBz.IsExist(o => o.UserName == entity.UserName && o.ID != entity.ID);
            if (ValidUser)
            {
                ViewBag.Msg = $"该用户已存在：{entity.UserName}！";
                return View("UserEidt", entity);
            }
            if (string.IsNullOrWhiteSpace(entity.UserName))
            {
                ViewBag.Msg = $"用户名不能为空";
                return View("UserEidt", entity);
            }
            if (entity.ID <= 0)
            {
                entity.Pwd = UserInfoBz.GetPwdAES("123456");
            }
            var isSuccess = UserInfoBz.SaveOrUpdate(entity, entity.ID > 0);
            if (isSuccess)
            {
                ViewBag.Msg = "保存成功！";
            }
            else
            {
                ViewBag.Msg = "保存失败！";
            }
            var model = UserInfoBz.Get(o => o.UserName == entity.UserName);
            return View("UserEidt", model);
        }
       
    }
}

ProductionManageSys/ProductionManage/Views/User/UpdatePwd.cshtml
@using Domain.Model;
@model UserInfo
@{
    ViewBag.Title = "UserConfig";
}

<div class="row">

    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
        <div class="widget am-cf">
            <div class="widget-head am-cf">
                <div class="widget-title am-fl">密码修改</div>
                <div class="widget-function am-fr">
                    <a href="javascript:;" class="am-icon-cog"></a>
                </div>
            </div>
            <div class="widget-body am-fr">  
                    <form class="am-form tpl-form-line-form">
                        <div class="am-form-group">
                            <label for="user-name" class="am-u-sm-3 am-form-label">旧密码</label>
                            <div class="am-u-sm-9">
                                @Html.TextBox("oldPwd", "", new { @class = "tpl-form-input", placeholder = "请输入旧密码" })
                            </div>
                        </div>
                        <div class="am-form-group">
                            <label for="user-name" class="am-u-sm-3 am-form-label">新密码</label>
                            <div class="am-u-sm-9">
                                @Html.TextBox("newPwd", "", new { @class = "tpl-form-input", placeholder = "请输入新密码" })
                            </div>
                        </div>
                        <div class="am-form-group">
                            <label for="user-name" class="am-u-sm-3 am-form-label">确认新密码</label>
                            <div class="am-u-sm-9">
                                @Html.TextBox("comfirmPwd", "", new { @class = "tpl-form-input", placeholder = "请再次输入新密码" })
                            </div>
                        </div>
                        <div class="am-form-group">
                            <div class="am-u-sm-9 am-u-sm-push-3">
                                <button type="button" class="am-btn am-btn-primary tpl-btn-bg-color-success " id="btnOK">提交</button>
                            </div>
                        </div>
                     
                    </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
      $(function(){
          if("@ViewBag.Msg"!="")
              layer.msg("@ViewBag.Msg");
          $("#btnOK").click(function () {
              submit();
          });
      });
    function submit() {
            var oldPwd = $("#oldPwd").val().trim();
            var newPwd = $("#newPwd").val().trim();
            var comfirmPwd = $("#comfirmPwd").val().trim();
            if (oldPwd == "") {
                layer.msg("请输入旧密码！");
                return false;
            }
            if (newPwd == "") {
                layer.msg("请输入新密码！");
                return false;
            }
            if (newPwd != comfirmPwd) {
                layer.msg("两次输入的新密码不一致！");
                return false;
            }
            $.ajax({
                url: "@Url.Action("SaveUpdatePwd")",
                dataType: "json",
            cache: false,
            data: $("form").serialize(),
            type: "POST",
            success: function (data) {
                if (data.isSuccess) {
                    layer.msg(data.Msg);
                    location.href = "@Url.Action("Index","Login")";
                }
                else {
                    layer.msg(data.Msg);
                }
            }
        }   );
        }
</script>

ProductionManageSys/ProductionManage/Views/User/UserConfig.cshtml
@using Domain.Model;
@model UserInfo
@{
    ViewBag.Title = "UserConfig";
}

<div class="row">

    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
        <div class="widget am-cf">
            <div class="widget-head am-cf">
                <div class="widget-title am-fl">账号设置</div>
                <div class="widget-function am-fr">
                    <a href="javascript:;" class="am-icon-cog"></a>
                </div>
            </div>
            <div class="widget-body am-fr">

                @using (Html.BeginForm("SaveUserConfig", "User", FormMethod.Post, new { @class = "am-form tpl-form-line-form" }))
                {
                    @Html.HiddenFor(o => o.ID, new { Value = Model?.ID })
                    <div class="am-form-group">
                        <label for="user-name" class="am-u-sm-3 am-form-label">用户名</label>
                        <div class="am-u-sm-9">
                            @Html.TextBoxFor(o => o.UserName, new { @class = "tpl-form-input", placeholder = "请输入用户名" })
                            <small>请填写汉字、字母、数字、下划线组合。</small>
                        </div>
                    </div>

                    <div class="am-form-group">
                        <label for="user-phone" class="am-u-sm-3 am-form-label">角色</label>
                        <div class="am-u-sm-9">
                            @Html.DropDownListFor(t => t.RoleID,
                                ViewBag.selectList as IEnumerable<SelectListItem>,
                                new { style = "background:#4b5357" })
                            
                        </div>
                    </div>
                    <div class="am-form-group">
                        <label for="user-intro" class="am-u-sm-3 am-form-label">是否生效</label>
                        <div class="am-u-sm-9">
                            @Html.CheckBoxFor(o => o.IsValid, new { @class = "ios-switch bigswitch tpl-switch-btn" })
                        </div>
                    </div>
                    <div class="am-form-group">
                        <label for="user-intro" class="am-u-sm-3 am-form-label">是否是超级管理员</label>
                        <div class="am-u-sm-9">
                            @Html.CheckBoxFor(o => o.IsSuperAdmin, new { @class = "ios-switch bigswitch tpl-switch-btn" })
                        </div>
                    </div>
                    <div class="am-form-group">
                        <label for="user-name" class="am-u-sm-3 am-form-label">头像</label>
                        <div class="am-u-sm-9">
                            @Html.TextBoxFor(o => o.HeadImgUrl, new { @class = "tpl-form-input", placeholder = "请选择图片" })
                        </div>
                    </div>
                    <div class="am-form-group">
                        <label for="user-name" class="am-u-sm-3 am-form-label"></label>
                        <div class="am-u-sm-9">
                            <div id="uploader-demo">
                                <!--用来存放item-->
                                <div id="fileList" class="uploader-list"></div>
                                <div id="filePicker1">
                                    @if (!string.IsNullOrWhiteSpace(Model?.HeadImgUrl))
                                    {
                                        <img id="pic1" src="@Model.HeadImgUrl" width="100" />
                                    }
                                    else
                                    {
                                        <img id="pic1" src="~/Content/Img/photo_icon.png" />
                                    }
                                    <span id="UploadStatus1" style="position:absolute;left:0;top:0; width:100%;background:red"></span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="am-form-group">
                        <div class="am-u-sm-9 am-u-sm-push-3">
                            <button type="submit" class="am-btn am-btn-primary tpl-btn-bg-color-success ">提交</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
      $(function(){
          if("@ViewBag.Msg"!="")
              layer.msg("@ViewBag.Msg");
       });
</script>
<script type="text/javascript">
        //1.
        $(function(){
            var uploader = WebUploader.create({

                // 选完文件后，是否自动上传。
                auto: true,

                // swf文件路径
                swf: 'https://cdn.staticfile.org/webuploader/0.1.5/Uploader.swf',

                // 文件接收服务端。
                server: '/Upload/UploadImg',

                // 选择文件的按钮。可选。
                // 内部根据当前运行是创建，可能是input元素，也可能是flash.
                pick: '#filePicker1',

                // 只允许选择图片文件。
                accept: {
                    title: 'Images',
                    extensions: 'gif,jpg,jpeg,bmp,png',
                    mimeTypes: 'image/*'
                }
            });
            // 当有文件添加进来的时候
            uploader.on( 'fileQueued', function( file ) {
                // $list为容器jQuery实例

                // 创建缩略图
                // 如果为非图片文件，可以不用调用此方法。
                // thumbnailWidth x thumbnailHeight 为 100 x 100
                uploader.makeThumb( file, function( error, src ) {
                    if ( error ) {
                        $img.replaceWith('<span>不能预览</span>');
                        return;
                    }
                    $("#pic1").attr("src",src)
                }, 300, 300 );
            });
            uploader.on( 'uploadProgress', function( file, percentage ) {
                var $li = $( '#'+file.id ),
                $percent = $li.find('.progress span');

                // 避免重复创建
                if ( !$percent.length ) {
                    $percent = $('<p class="progress"><span></span></p>')
                    .appendTo( $li )
                    .find('span');
                }

                $percent.css( 'width', percentage * 100 + '%' );
            });

            // 文件上传成功，给item添加成功class, 用样式标记上传成功。
            uploader.on('uploadSuccess', function (file, response) {
                $('#' + file.id).addClass('upload-state-done');
                if (response.isSuccess) {
                    $("#HeadImgUrl").val(response.ImgUrl);
                    $("#UploadStatus1").html('上传成功');
                }
            });

            // 文件上传失败，显示上传出错。
            uploader.on('uploadError', function (file) {
                $("#UploadStatus1").html('上传失败');
                $("#HeadImgUrl").val("");
            });

            // 完成上传完了，成功或者失败，先删除进度条。
            uploader.on( 'uploadComplete', function( file ) {
                $( '#'+file.id ).find('.progress').remove();
            });
        });
</script>

ProductionManageSys/ProductionManage/Views/User/UserEidt.cshtml
@using Domain.Model;
@model UserInfo
@{
    ViewBag.Title = "UserConfig";
}

<div class="row">

    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
        <div class="widget am-cf">
            <div class="widget-head am-cf">
                <div class="widget-title am-fl">编辑用户</div>
                <div class="widget-function am-fr">
                    <a href="javascript:;" class="am-icon-cog"></a>
                </div>
            </div>
            <div class="widget-body am-fr">

                @using (Html.BeginForm("UserSave", "User", FormMethod.Post, new { @class = "am-form tpl-form-line-form" }))
                {
                    @Html.HiddenFor(o => o.ID, new { Value = Model?.ID })
                    <div class="am-form-group">
                        <label for="user-name" class="am-u-sm-3 am-form-label">用户名</label>
                        <div class="am-u-sm-9">
                            @Html.TextBoxFor(o => o.UserName, new { @class = "tpl-form-input", placeholder = "请输入用户名" })
                            <small>请填写汉字、字母、数字、下划线组合。</small>
                        </div>
                    </div>

                    <div class="am-form-group">
                        <label for="user-phone" class="am-u-sm-3 am-form-label">角色</label>
                        <div class="am-u-sm-9">
                            @Html.DropDownListFor(t => t.RoleID,
                                ViewBag.selectList as IEnumerable<SelectListItem>,
                                new { style = "background:#4b5357" })
                           
                        </div>
                    </div>
                    <div class="am-form-group">
                        <label for="user-intro" class="am-u-sm-3 am-form-label">是否生效</label>
                        <div class="am-u-sm-9">
                            @Html.CheckBoxFor(o => o.IsValid, new { @class = "ios-switch bigswitch tpl-switch-btn" })
                        </div>
                    </div>
                    <div class="am-form-group">
                        <label for="user-intro" class="am-u-sm-3 am-form-label">是否是超级管理员</label>
                        <div class="am-u-sm-9">
                            @Html.CheckBoxFor(o => o.IsSuperAdmin, new { @class = "ios-switch bigswitch tpl-switch-btn" })
                        </div>
                    </div>
                    <div class="am-form-group">
                        <label for="user-name" class="am-u-sm-3 am-form-label">头像</label>
                        <div class="am-u-sm-9">
                            @Html.TextBoxFor(o => o.HeadImgUrl, new { @class = "tpl-form-input", placeholder = "请选择图片" })
                        </div>
                    </div>
                    <div class="am-form-group">
                        <label for="user-name" class="am-u-sm-3 am-form-label"></label>
                        <div class="am-u-sm-9">
                            <div id="uploader-demo">
                                <!--用来存放item-->
                                <div id="fileList" class="uploader-list"></div>
                                <div id="filePicker1">
                                    @if (!string.IsNullOrWhiteSpace(Model?.HeadImgUrl))
                                    {
                                        <img id="pic1" src="@Model.HeadImgUrl" width="100" />
                                    }
                                    else
                                    {
                                        <img id="pic1" src="~/Content/Img/photo_icon.png" />
                                    }
                                    <span id="UploadStatus1" style="position:absolute;left:0;top:0; width:100%;background:red"></span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="am-form-group">
                        <div class="am-u-sm-9 am-u-sm-push-3">
                            <button type="submit" class="am-btn am-btn-primary tpl-btn-bg-color-success ">提交</button>
                            <button type="button" class="am-btn am-btn-primary tpl-btn-bg-color-success " onclick="location.href='@Url.Action("UserManageIndex")'">返回</button>
                        </div>
                       
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
      $(function(){
          if("@ViewBag.Msg"!="")
              layer.msg("@ViewBag.Msg");
       });
</script>
<script type="text/javascript">
        //1.
        $(function(){
            var uploader = WebUploader.create({

                // 选完文件后，是否自动上传。
                auto: true,

                // swf文件路径
                swf: 'https://cdn.staticfile.org/webuploader/0.1.5/Uploader.swf',

                // 文件接收服务端。
                server: '/Upload/UploadImg',

                // 选择文件的按钮。可选。
                // 内部根据当前运行是创建，可能是input元素，也可能是flash.
                pick: '#filePicker1',

                // 只允许选择图片文件。
                accept: {
                    title: 'Images',
                    extensions: 'gif,jpg,jpeg,bmp,png',
                    mimeTypes: 'image/*'
                }
            });
            // 当有文件添加进来的时候
            uploader.on( 'fileQueued', function( file ) {
                // $list为容器jQuery实例

                // 创建缩略图
                // 如果为非图片文件，可以不用调用此方法。
                // thumbnailWidth x thumbnailHeight 为 100 x 100
                uploader.makeThumb( file, function( error, src ) {
                    if ( error ) {
                        $img.replaceWith('<span>不能预览</span>');
                        return;
                    }
                    $("#pic1").attr("src",src)
                }, 300, 300 );
            });
            uploader.on( 'uploadProgress', function( file, percentage ) {
                var $li = $( '#'+file.id ),
                $percent = $li.find('.progress span');

                // 避免重复创建
                if ( !$percent.length ) {
                    $percent = $('<p class="progress"><span></span></p>')
                    .appendTo( $li )
                    .find('span');
                }

                $percent.css( 'width', percentage * 100 + '%' );
            });

            // 文件上传成功，给item添加成功class, 用样式标记上传成功。
            uploader.on('uploadSuccess', function (file, response) {
                $('#' + file.id).addClass('upload-state-done');
                if (response.isSuccess) {
                    $("#HeadImgUrl").val(response.ImgUrl);
                    $("#UploadStatus1").html('上传成功');
                }
            });

            // 文件上传失败，显示上传出错。
            uploader.on('uploadError', function (file) {
                $("#UploadStatus1").html('上传失败');
                $("#HeadImgUrl").val("");
            });

            // 完成上传完了，成功或者失败，先删除进度条。
            uploader.on( 'uploadComplete', function( file ) {
                $( '#'+file.id ).find('.progress').remove();
            });
        });
</script>

ProductionManageSys/ProductionManage/Views/User/UserManageIndex.cshtml
@using Domain.Model;
@using Common;

@model PageInfo<UserInfo>
@{
    var viewName = "UserManageIndex";
    var rowStyle = "odd gradeX";
}
<div class="row">

    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
        <div class="widget am-cf">
            <div class="widget-head am-cf">
                <div class="widget-title am-fl">用户管理</div>
                <div class="widget-function am-fr">
                    <a href="javascript:;" class="am-icon-cog"></a>
                </div>
            </div>
            <div class="widget-body  am-fr">
                <div class="am-u-sm-12 am-u-md-6 am-u-lg-6">
                    <div class="am-form-group">
                        <div class="am-btn-toolbar">
                            <div class="am-btn-group am-btn-group-xs">
                                <button type="button" class="am-btn am-btn-default am-btn-success" onclick="location.href='@Url.Action("UserEidt")'"><span class="am-icon-plus"></span> 新增</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="am-u-sm-12 am-u-md-6 am-u-lg-6">
                    <div class="am-form-group">
                        <div class="am-btn-toolbar">
                            <div class="am-btn-group am-btn-group-xs">
                                @*  <button type="button" class="am-btn am-btn-default am-btn-success" onclick="location.href='@Url.Action("ApplyJobAdd")'"><span class="am-icon-plus"></span> 新增</button>*@
                            </div>
                        </div>
                    </div>
                </div>
                <div class="am-u-sm-12 am-u-md-12 am-u-lg-3">
                    <div class="am-input-group am-input-group-sm tpl-form-border-form cl-p">
                        <input class="am-form-field " type="text" id="txt_search" placeholder="请输入用户名称...">
                        <span class="am-input-group-btn">
                            <button class="am-btn  am-btn-default am-btn-success tpl-table-list-field am-icon-search" onclick="Search()" type="button"></button>
                        </span>
                    </div>
                </div>
                <div class="am-u-sm-12">
                    <table class="am-table am-table-compact am-table-striped tpl-table-black " id="example-r" width="100%">
                        <thead>
                            <tr>
                                <th>用户名</th>
                                <th>角色</th>
                                <th>是否生效</th>
                                <th>是否超级管理员</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var row in Model.List)
                            {
                                <tr class=@rowStyle>
                                    <td>@row.UserName</td>
                                    <td>@(((ViewBag.role as IQueryable<RoleInfo>).First(o => o.ID ==row.RoleID)).RoleName)</td>
                                    @if (row.IsValid)
                                    {
                                        <td>是</td>
                                    }
                                    else
                                    {
                                        <td>否</td>
                                    }
                                    
                                   @if (row.IsSuperAdmin)
                                   {
                                    <td>是</td>
                                   }
                                   else
                                   {
                                    <td>否</td>
                                   }
                                    <td>
                                        <div class="tpl-table-black-operation">
                                            <a href=@Url.Action("UserEidt", new { id=row.ID})>
                                                <i class="am-icon-pencil"></i> 修改
                                            </a>
                                            <a href=@Url.Action("UserDel", new { id=row.ID}) class="tpl-table-black-operation-del">
                                                <i class="am-icon-trash"></i> 删除
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                rowStyle = "even gradeC";
                            }
                        </tbody>
                    </table>
                </div>
                <div class="am-u-lg-12 am-cf">
                    <div class="am-fr">
                        <ul class="am-pagination tpl-pagination">
                            <li>
                                <a href=@Url.Action(viewName, new { p = 1,searchFild=ViewBag.searchFild })>«</a>
                            </li>
                            @for (int i = Model.Index - 4; i < Model.Index; i++)
                            {
                                if (i > 0)
                                {
                                    <li><a href=@Url.Action(viewName, new { p = i,searchFild=ViewBag.searchFild  })>@i</a></li>
                                }
                            }
                            <li class="am-active"><a href="#">@Model.Index</a></li>
                            @for (int i = 1; i <= 5; i++)
                            {
                                if (Model.Index + i <= Math.Ceiling((decimal)Model.Count / Model.PageSize))
                                {
                                    <li><a href=@Url.Action(viewName, new { p = Model.Index + i,searchFild=ViewBag.searchFild  })>@(@Model.Index + @i)</a></li>
                                }
                            }
                            <li>
                                <a href=@Url.Action(viewName, new { p = Math.Ceiling((decimal)Model.Count / Model.PageSize),searchFild=ViewBag.searchFild  })>»</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
      $(function(){
          if("@TempData["Msg"]"!="")
              layer.msg("@TempData["Msg"]");
       });
</script>
<script src="~/scripts/amazeui.datatables.min.js"></script>
@section scripts{

    function Search(){

    var value = $("#txt_search").val();

    location.href='@Url.Action("UserManageIndex")'+'?searchFild='+value;

    }
}