ProductionManageSys/ProductionManage/Controllers/BOMController.cs
using Domain.Model;
using Service.IService;
using Service.ServiceImp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionManage.Controllers
{
    public class BOMController : BaseController
    {
        public IBOMManage BOMBz = new BOMManage();
        // GET: ProductionBOM
        public ActionResult Index(int p = 1, string searchFild = "")
        {
            var model = BOMBz.Query(
                         BOMBz.LoadAll(o => o.ParentModuleID==0 && o.ModuleName.Contains(searchFild)).OrderByDescending(o => o.ID),
                         p,
                         10);
            ViewBag.searchFild = searchFild;
            return View(model);
        }
        public ActionResult BOMAdd()
        {
            return View();
        }
        public  ActionResult BOMEidt(string ModuleName)
        {
            var entity = BOMBz.LoadAll(o => o.TopModuleName== ModuleName).ToList();
            string data = "[";
            foreach (var row in entity)
            {
                data += " { id: "+row.ID+", pId: "+row.ParentModuleID+", name: \""+row.ModuleName+ "\"" +", num: \"" + row.ModuleNum + "\", open: true ,isProduct:true},";
                for(int i=0; i<row.ProductBom.Count;i++){
                    data += " { id: " + row.ProductBom[i].BOMID+i.ToString() + ", pId: " + row.ProductBom[i].BOMID + ", name: \"" + row.ProductBom[i].ProductName + "\""+", num: \"" + row.ProductBom[i].Num + "\" , open: true ,isProduct:true},";
                }
            }
            data = data.Substring(0, data.Length - 1) + "]";
            ViewBag.data = data;
            return View(entity);
        }

    }
}

ProductionManageSys/ProductionManage/Controllers/LayerController.cs
using ProductionManage.Models;
using Service.IService;
using Service.ServiceImp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionManage.Controllers
{
    public class LayerController : BaseController
    {
        public ISupplierProductManage SupplierProductManageBz = new SupplierProductManage();
        public IPurchaseOrderManage PurchaseOrderManageBz = new PurchaseOrderManage();
        public IProductManage ProductManageBz = new ProductManage();
        public SupplierManage SupplierManageBz = new SupplierManage();
        // GET: Layer
        [AllowAnonymous]
        public ActionResult ProductList(string SupplierName,string filter, int p = 1, string searchFild = "")
        {
            var arr = filter.Split('|');
            ViewBag.filter = filter;
            var supplierModel = SupplierManageBz.Get(o => o.CorpName == SupplierName);
            if (supplierModel != null) {
                int SupplierId = supplierModel.ID;
                var model = SupplierProductManageBz.Query(
                               SupplierProductManageBz.LoadAll(o => o.SupplierId == SupplierId && !arr.Contains(o.ProductName) && o.ProductName.Contains(searchFild)).OrderByDescending(o => o.ProductId),
                               p,
                               10);
                ViewBag.searchFild = searchFild;
                return View(model);
            }
            else
            {
                return  View();
            }
        }
        /// <summary>
        /// 产品库存
        /// </summary>
        /// <param name="SupplierName"></param>
        /// <param name="filter"></param>
        /// <param name="p"></param>
        /// <param name="searchFild"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult ProductStockList(string filter, int p = 1, string searchFild = "")
        {
            var arr = filter.Split('|');
            ViewBag.filter = filter;

            var model = ProductManageBz.Query(
                            ProductManageBz.LoadAll(o=>!arr.Contains(o.ProductName) && o.ProductName.Contains(searchFild)).OrderByDescending(o => o.ProductId),
                            p,
                            10);
            ViewBag.searchFild = searchFild;
            return View(model);
        }
        [AllowAnonymous]
        public ActionResult PurchaseOrderListForAccept(string searchFild = "", int p = 1)
        {
                var model = PurchaseOrderManageBz.Query(
                               PurchaseOrderManageBz.LoadAll(o => (o.Status==OrderStatus.待验收 || o.Status == OrderStatus.部分验收) && o.PurchaseOrderNo.Contains(searchFild)).OrderByDescending(o => o.ID),
                               p,
                               10);
                ViewBag.searchFild = searchFild;
                return View(model);
        }
    }
}

ProductionManageSys/ProductionManage/Controllers/PurcahseController.cs
using Domain.Model;
using ProductionManage.Models;
using Service;
using Service.IService;
using Service.ServiceImp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionManage.Controllers
{
    public class PurcahseController : BaseController
    {
        public IPurchaseOrderManage PurchaseOrderManageBz = new PurchaseOrderManage();
        public ISupplier  SupplierManageBz = new SupplierManage();
        // GET: Purcahse  
        public ActionResult Index(int p = 1, string searchFild = "")
        {
            var model = PurchaseOrderManageBz.Query(
                            PurchaseOrderManageBz.LoadAll(o => o.PurchaseOrderNo.Contains(searchFild)).OrderByDescending(o => o.ID),
                            p,
                            10);
            ViewBag.searchFild = searchFild;
           
            return View(model);
        }
        public ActionResult PurchaseEidt(string PurchaseOrderNo = "",string Msg="")
        {
            var model = PurchaseOrderManageBz.Get(o => o.PurchaseOrderNo == PurchaseOrderNo);
            if (model!=null &&　model.Status != OrderStatus.未审批)
            {
                TempData["Msg"] = "此订单非未审批状态，无法修改！";
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.GetSupplierList = GetSupplierList();
                ViewBag.Msg = Msg;
                return View(model);
            }
        }
        public ActionResult PurchaseDetail(string PurchaseOrderNo = "", string Msg = "")
        {
            var model = PurchaseOrderManageBz.Get(o => o.PurchaseOrderNo == PurchaseOrderNo);
            ViewBag.GetSupplierList = GetSupplierList();
            ViewBag.Msg = Msg;
            return View(model);
        }
        /// <summary>
        /// 供应商列表
        /// </summary>
        /// <returns></returns>
        public  List<SelectListItem> GetSupplierList()
        {
            var list= SupplierManageBz.LoadAll(o => true).Select(o => new SelectListItem { Text = o.CorpName, Value = o.CorpName.ToString() }).ToList();
            list.Insert(0, new SelectListItem
            {
                Text = "请选择",
                Value = ""
            });
            return list;  
        }
        
        public ActionResult PurchaseDel(int id)
        {
            var model = PurchaseOrderManageBz.Get(o => o.ID == id);
            if (model.Status != OrderStatus.未审批)
            {
                TempData["Msg"] = "此订单非未审批状态，无法删除！";
            }
            else
            {
                var isSuccess = PurchaseOrderManageBz.Delete(o => o.ID == id);
                if (isSuccess)
                {
                    TempData["Msg"] = "删除成功！";
                }
                else
                {
                    TempData["Msg"] = "删除失败！";
                }
            }
            
            return RedirectToAction("Index");
        }
        public ActionResult Save(PurchaseOrder model)
        {
            try
            {
                var PurchaseOrderNo = model.PurchaseOrderNo ?? "";
                //验证
                if (string.IsNullOrEmpty(model.Supplier)){
                    ViewBag.Msg = "请选择供应商";
                    return View("PurchaseEidt", model);
                }
                if (string.IsNullOrEmpty(model.PurchaseDate))
                {
                    ViewBag.Msg = "请选择采购日期";
                    return View("PurchaseEidt", model);
                }
                if (string.IsNullOrEmpty(model.Supplier))
                {
                    ViewBag.Msg = "请选择采购日期";
                    return View("PurchaseEidt", model);
                }
               
                model.PurchaseOrderDetail = model.PurchaseOrderDetail?.Where(o => o.ProductName !=null && o.ProductName != "").ToList();
                if (model.PurchaseOrderDetail==null || !model.PurchaseOrderDetail.Any())
                {
                    ViewBag.Msg = "请选择需采购产品";
                    return View("PurchaseEidt", model);
                }

                if (string.IsNullOrWhiteSpace(PurchaseOrderNo))//新增
                {
                    model.PurchaseOrderNo = Common.Utils.GetOrderNumber();
                    while (PurchaseOrderManageBz.IsExist(o => o.PurchaseOrderNo == model.PurchaseOrderNo))
                    {
                        model.PurchaseOrderNo = Common.Utils.GetOrderNumber();
                    }
                    model.Purchaser = CurrentUser.UserName;
                    model.Status = OrderStatus.未审批;
                    float sumPriceTotal = 0;
                    int sumNumTotal = 0;
                    foreach (PurchaseOrderDetail detail in model.PurchaseOrderDetail)
                    {
                        float price = detail.Price;
                        int num = detail.PurchaseNum;
                        float sumprice = price * (num);
                        sumPriceTotal += sumprice;
                        sumNumTotal += (num);
                        detail.SumPrice = sumprice;
                        detail.PurchaseNumOver = 0;
                        detail.PurchaseNumWait = num;
                    }
                    model.SumPrice = sumPriceTotal;
                    model.PurchaseNum = sumNumTotal;
                    model.PurchaseNumWait = sumNumTotal;
                    model.Oper = CurrentUser.UserName;
                    bool isSuccess = PurchaseOrderManageBz.Save(model);
                    ViewBag.Msg = isSuccess ? "保存成功！" : "保存失败！";
                   
                }
                else
                {
                    var oldData = PurchaseOrderManageBz.Get(o => o.PurchaseOrderNo == model.PurchaseOrderNo);
                    var newData = Common.Tools.CopyObjectValue(oldData, model);
                    newData.PurchaseOrderDetail.ForEach(o => o.PurchaseOrderId = newData.ID);

                    newData.Status = OrderStatus.未审批;
                    float sumPriceTotal = 0;
                    int sumNumTotal = 0;
                    foreach (PurchaseOrderDetail detail in newData.PurchaseOrderDetail)
                    {
                        float price = detail.Price;
                        int num = detail.PurchaseNum;
                        float sumprice = price * num;
                        
                        sumPriceTotal += sumprice;
                        sumNumTotal += num;
                        detail.SumPrice = sumprice;
                        detail.PurchaseNumOver = 0;
                        detail.PurchaseNumWait = num;
                    }
                    
                    newData.SumPrice = sumPriceTotal;
                    newData.PurchaseNum = sumNumTotal;
                    newData.PurchaseNumWait = sumNumTotal;
                    newData.Oper = CurrentUser.UserName;
                    if (newData.Status == OrderStatus.未审批)
                    {
                        bool isSuccess = PurchaseOrderManageBz.Update(newData);
                        ViewBag.Msg = isSuccess ? "保存成功！" : "保存失败！";
                    }
                    else
                    {
                        ViewBag.Msg = $"订单{newData.PurchaseOrderNo}，修改失败！";
                    }
                }
               
                 return RedirectToAction("PurchaseEidt", new { PurchaseOrderNo = model.PurchaseOrderNo,Msg=ViewBag.Msg });
            }
            catch (Exception ex)
            {
                ViewBag.Msg = ex.Message;
                return View("PurchaseEidt", model);
            }
        }
        
        public ActionResult PurchaseApprove(int id)
        {
            var model=PurchaseOrderManageBz.Get(o => o.ID == id);
            if (model.Status != OrderStatus.未审批)
            {
                TempData["Msg"] = "此订单非未审批状态，无法审批！";
            }
            else
            {
                model.Status = OrderStatus.待验收;
                model.Oper = CurrentUser.UserName;
                var isSuccess = PurchaseOrderManageBz.Update(model);
                if (isSuccess)
                {
                    TempData["Msg"] = "审批成功！";
                }
                else
                {
                    TempData["Msg"] = "审批失败！";
                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult PurchaseReject(int id)
        {
            var model = PurchaseOrderManageBz.Get(o => o.ID == id);
            if (model.Status != OrderStatus.待验收)
            {
                TempData["Msg"] = "此订单非待验收状态，无法驳回！";
            }
            else
            {
                model.Status = OrderStatus.未审批;
                model.Oper = CurrentUser.UserName;
                var isSuccess = PurchaseOrderManageBz.Update(model);
                if (isSuccess)
                {
                    TempData["Msg"] = "驳回成功！";
                }
                else
                {
                    TempData["Msg"] = "驳回失败！";
                }
            }
            return RedirectToAction("Index");
        }
 
    }
}

ProductionManageSys/ProductionManage/Views/BOM/BOMAdd.cshtml
@using Domain.Model;
@using ProductionManage.Controllers;
@model PurchaseOrder
@{
    var viewName = "Index";
}
<style>
    .theme-black .tpl-table-black tbody > tr > td {
        border: 0;
    }
    .ztree li a {
       
    }
</style>
<link rel="stylesheet" href="~/Content/Css/zTreeStyle.css">
@using (Html.BeginForm("Save", "Purcahse", FormMethod.Post, new { @class = "am-form tpl-form-line-form" }))
{
    <div class="row">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
            <div class="widget am-cf">
                <div class="widget-head am-cf">
                    <div class="widget-title am-fl">编辑生产BOM</div>
                    <div class="widget-function am-fr" style="font-size:8px">
                        当前操作：选择产品->选择产品->选择产品
                    </div>

                </div>
                <div class="widget-body am-fr">
                    <div style="padding:5px">
                        <div class="am-form-group">
                            @*tree*@
                            <div class="am-u-sm-3">
                                <ul id="tree" class="ztree" style="width:100%; overflow:auto;"></ul>
                            </div>
                            @*tree edit*@
                            <div class="am-u-sm-9">
                             
                                <div class="am-form-group">
                                    <label for="user-name" class="am-u-sm-1 am-form-label">备注</label>
                                    <div class="am-u-sm-3">
                                        @Html.TextBoxFor(o => o.Remark, new { @class = "tpl-form-input", placeholder = "请输入备注" })
                                    </div>

                                    <label for="user-name" class="am-u-sm-1 am-form-label">备注</label>
                                    <div class="am-u-sm-3">
                                        @Html.TextBoxFor(o => o.Remark, new { @class = "tpl-form-input", placeholder = "请输入备注" })
                                    </div>

                                    <label for="user-name" class="am-u-sm-1 am-form-label">备注</label>
                                    <div class="am-u-sm-3">
                                        @Html.TextBoxFor(o => o.Remark, new { @class = "tpl-form-input", placeholder = "请输入备注" })
                                    </div>

                                </div>
                                <div class="am-form-group">
                                    <label for="user-name" class="am-u-sm-1 am-form-label">备注</label>
                                    <div class="am-u-sm-3">
                                        @Html.TextBoxFor(o => o.Remark, new { @class = "tpl-form-input", placeholder = "请输入备注" })
                                    </div>

                                    <label for="user-name" class="am-u-sm-1 am-form-label">备注</label>
                                    <div class="am-u-sm-3">
                                        @Html.TextBoxFor(o => o.Remark, new { @class = "tpl-form-input", placeholder = "请输入备注" })
                                    </div>

                                    <label for="user-name" class="am-u-sm-1 am-form-label">备注</label>
                                    <div class="am-u-sm-3">
                                        @Html.TextBoxFor(o => o.Remark, new { @class = "tpl-form-input", placeholder = "请输入备注" })
                                    </div>

                                </div>
                                <div class="am-form-group">
                                    <label for="user-name" class="am-u-sm-1 am-form-label">备注</label>
                                    <div class="am-u-sm-3">
                                        @Html.TextBoxFor(o => o.Remark, new { @class = "tpl-form-input", placeholder = "请输入备注" })
                                    </div>

                                    <label for="user-name" class="am-u-sm-1 am-form-label">备注</label>
                                    <div class="am-u-sm-3">
                                        @Html.TextBoxFor(o => o.Remark, new { @class = "tpl-form-input", placeholder = "请输入备注" })
                                    </div>

                                    <label for="user-name" class="am-u-sm-1 am-form-label">备注</label>
                                    <div class="am-u-sm-3">
                                        @Html.TextBoxFor(o => o.Remark, new { @class = "tpl-form-input", placeholder = "请输入备注" })
                                    </div>
                                </div>
                            </div>
                        </div>                       
                    </div>
                </div>
            </div>
        </div>
        <div class="am-form-group">
            <div class="am-u-sm-7 am-u-sm-push-5">
                <button type="submit" class="am-btn am-btn-primary tpl-btn-bg-color-success ">提交</button>
                <button type="button" class="am-btn am-btn-primary tpl-btn-bg-color-success " onclick="location.href='@Url.Action("Index")'">返回</button>
            </div>
        </div>
        <input type="hidden" id="hiddenProductId" />
        <input type="hidden" id="hiddenProdcutName" />
        <input type="hidden" id="hiddenproductPrice" />
    </div>
}
<script src="~/Scripts/jquery.ztree.all.min.js"></script>
<script type="text/javascript">
    var setting = {
        edit: {
            enable: false
        },
        view: {
            addHoverDom: addHoverDom,
            removeHoverDom: removeHoverDom,
            dblClickExpand: false,
            showLine: true,
            selectedMulti: false
        },
        data: {
            simpleData: {
                enable: true,
                idKey: "id",
                pIdKey: "pId",
                rootPId: ""
            }
        },
        callback: {
            beforeClick: function (treeId, treeNode) {
               
            }
        }
    };

    var zNodes = [
		{ id: 1, pId: 0, name: "[core] 基本功能 演示", open: true ,"isModule":true},
		{ id: 101, pId: 1, name: "最简单的树 --  标准 JSON 数据", file: "core/standardData" },
		{ id: 102, pId: 1, name: "最简单的树 --  简单 JSON 数据", file: "core/simpleData" },
		{ id: 103, pId: 1, name: "不显示 连接线", file: "core/noline" },
		{ id: 104, pId: 1, name: "不显示 节点 图标", file: "core/noicon" },
		{ id: 105, pId: 1, name: "自定义图标 --  icon 属性", file: "core/custom_icon" },
		{ id: 106, pId: 1, name: "自定义图标 --  iconSkin 属性", file: "core/custom_iconSkin" },
		{ id: 107, pId: 1, name: "自定义字体", file: "core/custom_font" },
		{ id: 115, pId: 1, name: "超链接演示", file: "core/url" },
		{ id: 108, pId: 1, name: "异步加载 节点数据", file: "core/async" },
		{ id: 109, pId: 1, name: "用 zTree 方法 异步加载 节点数据", file: "core/async_fun" },
		{ id: 110, pId: 1, name: "用 zTree 方法 更新 节点数据", file: "core/update_fun" },
		{ id: 111, pId: 1, name: "单击 节点 控制", file: "core/click" },
		{ id: 112, pId: 1, name: "展开 / 折叠 父节点 控制", file: "core/expand" },
		{ id: 113, pId: 1, name: "根据 参数 查找 节点", file: "core/searchNodes" },
		{ id: 114, pId: 1, name: "其他 鼠标 事件监听", file: "core/otherMouse" }
    ];

      $(function(){
          if("@ViewBag.Msg"!="")
              layer.msg("@ViewBag.Msg");
          InitTree();

      });
    function InitTree() {
        var t = $("#tree");
        t = $.fn.zTree.init(t, setting, zNodes);
        demoIframe = $("#testIframe");
        demoIframe.bind("load", loadReady);
        var zTree = $.fn.zTree.getZTreeObj("tree");
        zTree.selectNode(zTree.getNodeByParam("id", 101));

    }
    function addHoverDom(treeId, treeNode) {
        var sObj = $("#" + treeNode.tId + "_span");
        if (treeNode.editNameFlag || $("#addModule_" + treeNode.tId).length > 0) return;
        var addStr = "<span class='button ico_close' id='addModule_" + treeNode.tId
            + "' title='添加模块' onfocus='this.blur();'></span>";
        addStr += "<span class='button ico_docu' id='addProduct_" + treeNode.tId
           + "' title='添加产品' onfocus='this.blur();'></span>";
        sObj.after(addStr);
        var btn = $("#addModule_" + treeNode.tId);
        if (btn) btn.bind("click", function () {
         
        });
    };
    function removeHoverDom(treeId, treeNode) {
        $("#addModule_" + treeNode.tId).unbind().remove();
        $("#addProduct_" + treeNode.tId).unbind().remove();
    };

    function beforeDrag(treeId, treeNodes) {
        return false;
    }
    function AddRow() {
        if ($("#Supplier").val().trim() == "") {
            layer.msg("请先选择供应商！");
            return;
        } else {
            $("#fieldSupplier").find("button").attr("disabled", "disabled");
        }
        var length = $("#tb tbody tr").length;
        var data = "<tr class=\"odd gradeX\">";
        data+= "<input id=\"PurchaseOrderDetail_"+length+"__ProductId\" name=\"PurchaseOrderDetail["+length+"].ProductId\" type=\"hidden\" value=\"\">";
        data=data+"<td><input class=\"tpl-form-input\" id=\"PurchaseOrderDetail_"+length+"__ProductName\" name=\"PurchaseOrderDetail["+length+"].ProductName\" onclick=\"openWin(this)\" placeholder=\"请选择产品\" type=\"text\" value=\"\"></td>";
        data = data + "<td><input class=\"tpl-form-input\" readonly=\"true\" id=\"PurchaseOrderDetail_" + length + "__Price\" name=\"PurchaseOrderDetail[" + length + "].Price\" onkeyup=\"ValidNum(this);\" placeholder=\"\" type=\"text\" value=\"\"></td>";
        data=data+"<td><input class=\"input_number\" id=\"PurchaseOrderDetail_"+length+"__PurchaseNum\" name=\"PurchaseOrderDetail["+length+"].PurchaseNum\" onkeyup=\"ValidNum(this,true);Cal(this)\" placeholder=\"请输入数量\" type=\"text\" value=\"\"></td>";
        data = data + "<td><input class=\"tpl-form-input\" readonly=\"true\" id=\"PurchaseOrderDetail_" + length + "__SumPrice\" name=\"PurchaseOrderDetail[" + length + "].SumPrice\" onkeyup=\"ValidNum(this);\" placeholder=\"\" type=\"text\" value=\"\"></td>";
        data=data+"<td><input class=\"tpl-form-input\" id=\"PurchaseOrderDetail_"+length+"__Remark\" name=\"PurchaseOrderDetail["+length+"].Remark\" placeholder=\"请输入备注\" type=\"text\" value=\"\"></td>";
        data=data+"<td>";
        data=data+"<div class=\"tpl-table-black-operation\">";
        data=data+"<a href=\"#\" class=\"tpl-table-black-operation-del\" onclick=\"DelRow(this)\">";
        data=data+"<i class=\"am-icon-trash\"></i> 删除";
        data=data+"</a>";
        data=data+"</div>";
        data=data+"</td>";
        data=data+"</tr>";
        $("#tb tbody").append(data);
    }
    function DelRow(obj) {
        $(obj).parents("tr").find("[name*='ProductName']").val("");
        $(obj).parents("tr").find("[name*='Price']").val("0");
        $(obj).parents("tr").attr("style","display:none");
        if ($("#tb tbody").find("tr").not("[style]").length <= 0) {
            $("#fieldSupplier").find("button").removeAttr("disabled");
        } else {
            $("#fieldSupplier").find("button").attr("disabled");
        }
        CalAll();
    }
    function Cal(obj) {
        var num = $(obj).val();
        var PurchaseOrderDetail_Price = $(obj).parents("tr").find("[name*='Price']").val();
        console.log(num);
        console.log(PurchaseOrderDetail_Price);
        $(obj).parents("tr").find("[name*='SumPrice']").val(Math.round(parseInt(num) * parseFloat(PurchaseOrderDetail_Price)*100)/100);
        CalAll();
    }
    function CalAll() {
        var sum = 0;
        $.each($("#tb tbody tr"), function (index, data) {
            var PurchaseOrderDetail_Price = $(data).find("[name*='Price']").val();
            var PurchaseOrderDetail_PurchaseNum = $(data).find("[name*='PurchaseNum']").val();

            sum = Math.round((sum + parseFloat(PurchaseOrderDetail_Price) * parseInt(PurchaseOrderDetail_PurchaseNum))* 100)  / 100;
        });
        $("#SumPrice").val(sum);
    }
    function openWin(obj) {
        var SupplierName = $("#Supplier").val();
        var productNameArr = $("#tb tbody tr").find("[name*='ProductName']");
        var filter = "";
        $.each(productNameArr, function (index, data) {
            filter += $(data).val() + "|";
        });
        layer.open({
            type: 2,
            title: '选择产品',
            shadeClose: true,
            id: "main",
            shade: true,
            offset: '100px',
            shade: 0.8,
            area: '80%',
            content: ['@Url.Action("ProductList", "Layer")' + "?SupplierName=" + SupplierName + "&filter=" + filter, 'no'],
            end: function () {
                var hiddenProdcutName = $("#hiddenProdcutName").val();
                var hiddenproductPrice = $("#hiddenproductPrice").val();
                var hiddenProductId = $("#hiddenProductId").val();
                if (hiddenProdcutName == "" || hiddenproductPrice == "" || hiddenProductId == "") return;
                $("#hiddenProdcutName").val("");
                $("#hiddenproductPrice").val("");
                $("#hiddenProductId").val("");
                $(obj).parents("tr").find("[name*='ProductId']").val(hiddenProductId);
                $(obj).parents("tr").find("[name*='ProductName']").val(hiddenProdcutName);
                $(obj).parents("tr").find("[name*='ProductName']").val(hiddenProdcutName);
                $(obj).parents("tr").find("[name*='Price']").val(hiddenproductPrice);
                $(obj).parents("tr").find("[name*='PurchaseNum']").val("1");
                $(obj).parents("tr").find("[name*='SumPrice']").val(hiddenproductPrice);
                $(obj).parents("tr").find("[name*='Remark']").val("");
                CalAll();
            }
        });
    }
</script>