ProductionManageSys/ProductionManage/Controllers/AcceptOrderController.cs
using Domain.Model;
using ProductionManage.Models;
using Service;
using Service.IService;
using Service.Model;
using Service.ServiceImp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionManage.Controllers
{
    public class AcceptOrderController : BaseController
    {
        public IAcceptOrderManage AcceptOrderManageBz = new AcceptOrderManage();
        public IProductManage ProductManageBz = new ProductManage();
        public IProductLogManage ProductLogManageBz = new ProductLogManage();
        public IPurchaseOrderManage PurchaseOrderManageBz = new PurchaseOrderManage();
        public ISupplier SupplierManageBz = new SupplierManage();
        // GET: AcceptOrder
        public ActionResult Index(int p = 1, string searchFild = "")
        {
            var model = AcceptOrderManageBz.Query(
                            AcceptOrderManageBz.LoadAll(o => o.AcceptOrderNo.Contains(searchFild)).OrderByDescending(o => o.ID),
                            p,
                            10);
            ViewBag.searchFild = searchFild;

            return View(model);
        }
        public ActionResult AcceptAdd()
        {
            var acceptorder = new AcceptOrderView();
            return View("AcceptEidt", acceptorder);
        }
        public ActionResult AcceptDetail(string AcceptOrderNo = "")
        {

            var model = AcceptOrderManageBz.Get(o => o.AcceptOrderNo == AcceptOrderNo);
            var purchaseOrder = PurchaseOrderManageBz.Get(o => o.PurchaseOrderNo == model.PurchaseOrderNo).PurchaseOrderDetail;
            if (model == null || purchaseOrder == null)
            {
                return HttpNotFound();
            }

            var acceptorder = new AcceptOrderView
            {
                AcceptDate = model.AcceptDate,
                Accepter = model.Accepter,
                AcceptNum = model.AcceptNum,
                AcceptOrderNo = model.AcceptOrderNo,
                Oper = model.Oper,
                ID = model.ID,
                PurchaseOrderNo = model.PurchaseOrderNo,
                Remark = model.Remark,
                Status = model.Status,
                SumPrice = model.SumPrice,
                AcceptOrderDetailView = new List<AcceptOrderDetailView>()
            };
            foreach (var row in purchaseOrder)
            {
                var acceptOrderDetail = model.AcceptOrderDetail.Find(o => o.ProductId == row.ProductId);
                acceptorder.AcceptOrderDetailView.Add(
                    new AcceptOrderDetailView
                    {
                        AcceptNum = acceptOrderDetail?.AcceptNum ?? 0,
                        AcceptOrderId = acceptOrderDetail?.AcceptOrderId ?? 0,
                        Price = row.Price,
                        ProductId = row.ProductId,
                        ProductName = row.ProductName,
                        Remark = row.Remark,
                        SumPrice = acceptOrderDetail?.SumPrice ?? 0,
                        PurchaseNum = row.PurchaseNum,
                        PurchaseNumWait = purchaseOrder.Find(o => o.ProductId == row.ProductId).PurchaseNumWait
                    });
            }
            return View(acceptorder);
        }
        
        public ActionResult AcceptEidt(string AcceptOrderNo = "", string Msg = "")
        {
            var model = AcceptOrderManageBz.Get(o => o.AcceptOrderNo == AcceptOrderNo);
            var purchaseOrder = PurchaseOrderManageBz.Get(o => o.PurchaseOrderNo == model.PurchaseOrderNo).PurchaseOrderDetail;
            if (model == null || purchaseOrder == null)
            {
                return HttpNotFound();
            }
            if (model != null && model.Status != OrderStatus.未审批)
            {
                TempData["Msg"] = "此订单非未审批状态，无法修改！";
                return RedirectToAction("Index");
            }

            var acceptorder = new AcceptOrderView
            {
                AcceptDate = model.AcceptDate,
                Accepter = model.Accepter,
                AcceptNum = model.AcceptNum,
                AcceptOrderNo = model.AcceptOrderNo,
                Oper = model.Oper,
                ID = model.ID,
                PurchaseOrderNo = model.PurchaseOrderNo,
                Remark = model.Remark,
                Status = model.Status,
                SumPrice = model.SumPrice,
                AcceptOrderDetailView = new List<AcceptOrderDetailView>()
            };
            foreach (var row in purchaseOrder)
            {
                var acceptOrderDetail = model.AcceptOrderDetail.Find(o => o.ProductId == row.ProductId);
                acceptorder.AcceptOrderDetailView.Add(
                    new AcceptOrderDetailView
                    {
                        AcceptNum = acceptOrderDetail?.AcceptNum??0,
                        AcceptOrderId = acceptOrderDetail?.AcceptOrderId??0,
                        Price = row.Price,
                        ProductId = row.ProductId,
                        ProductName = row.ProductName,
                        Remark = row.Remark,
                        SumPrice = acceptOrderDetail?.SumPrice??0,
                        PurchaseNum = row.PurchaseNum,
                        PurchaseNumWait = purchaseOrder.Find(o => o.ProductId == row.ProductId).PurchaseNumWait
                    });
            }
            ViewBag.Msg = Msg;
            return View(acceptorder);
        }
        public ActionResult Save(AcceptOrderView model)
        {
            try
            {
                var AcceptOrderView = model.AcceptOrderNo ?? "";
                //验证
                if (string.IsNullOrEmpty(model.PurchaseOrderNo))
                {
                    ViewBag.Msg = "请选择需验收的采购订单";
                    return View("AcceptEidt", model);
                }
                if (string.IsNullOrEmpty(model.AcceptDate))
                {
                    ViewBag.Msg = "请选择验收日期";
                    return View("AcceptEidt", model);
                }

               


                var purchaseModel = PurchaseOrderManageBz.Get(o => o.PurchaseOrderNo == model.PurchaseOrderNo);
                if (string.IsNullOrWhiteSpace(AcceptOrderView))//新增
                {
                    model.AcceptOrderNo = Common.Utils.GetOrderNumber();
                    while (AcceptOrderManageBz.IsExist(o => o.AcceptOrderNo == model.AcceptOrderNo))
                    {
                        model.AcceptOrderNo = Common.Utils.GetOrderNumber();
                    }
                    
                    var acceptOrder = AcceptOrderViewToAcceptOrder(model);
                    if (model.AcceptNum <= 0)
                    {
                        ViewBag.Msg = "请输入验收数量";
                        return View("AcceptEidt", model);
                    }
                    acceptOrder.Oper = CurrentUser.UserName;
                    bool isSuccess = AcceptOrderManageBz.Save(acceptOrder);
                    ViewBag.Msg = isSuccess ? "保存成功！" : "保存失败！";

                }
                else
                {
                    var acceptOrder = AcceptOrderViewToAcceptOrder(model);

                    var oldData = AcceptOrderManageBz.Get(o => o.AcceptOrderNo == model.AcceptOrderNo);
                    var newData = Common.Tools.CopyObjectValue(oldData, acceptOrder);
                    newData.AcceptOrderDetail.ForEach(o => o.AcceptOrderId = newData.ID);
                    if (newData.AcceptNum <= 0)
                    {
                        ViewBag.Msg = "请输入验收数量";
                        return View("AcceptEidt", model);
                    }
                    if (newData.Status == OrderStatus.未审批)
                    {
                        //purchaseModel.PurchaseNumOver = purchaseModel.PurchaseNumOver + model.AcceptNum;
                        //purchaseModel.PurchaseNumWait = purchaseModel.PurchaseNumWait - model.AcceptNum;
                        //foreach (var row in acceptOrder.AcceptOrderDetail)
                        //{
                        //    var purchaseDetailModel = purchaseModel.PurchaseOrderDetail.Find(o => o.ProductId == row.ProductId);
                        //    purchaseDetailModel.PurchaseNumOver += row.AcceptNum;
                        //    purchaseDetailModel.PurchaseNumWait -= row.AcceptNum;
                        //}
                        newData.Oper = CurrentUser.UserName;
                        bool isSuccess = AcceptOrderManageBz.Update(newData);
                        ViewBag.Msg = isSuccess ? "保存成功！" : "保存失败！";
                    }
                    else
                    {
                        ViewBag.Msg = $"订单{newData.AcceptOrderNo}，修改失败！";
                    }
                }

                return RedirectToAction("AcceptEidt", new { AcceptOrderNo = model.AcceptOrderNo, Msg = ViewBag.Msg });
            }
            catch (Exception ex)
            {
                ViewBag.Msg = ex.Message;
                return View("PurchaseEidt", model);
            }
        }
        private AcceptOrder AcceptOrderViewToAcceptOrder(AcceptOrderView  model)
        {
            model.Accepter = CurrentUser.UserName;
            model.Status = OrderStatus.未审批;

            float sumPriceTotal = 0;
            int sumNumTotal = 0;
            foreach (var detail in model.AcceptOrderDetailView)
            {
                float price = detail.Price;
                int num = detail.AcceptNum;
                float sumprice = price * num;
                sumPriceTotal += sumprice;
                sumNumTotal += num;
                detail.SumPrice = sumprice;
            }
            model.SumPrice = sumPriceTotal;
            model.AcceptNum = sumNumTotal;

            var acceptorder = new AcceptOrder
            {
                AcceptDate = model.AcceptDate,
                Accepter = model.Accepter,

ProductionManageSys/ProductionManage/Controllers/LayerController.cs
using ProductionManage.Models;
using Service.IService;
using Service.ServiceImp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionManage.Controllers
{
    public class LayerController : BaseController
    {
        public ISupplierProductManage SupplierProductManageBz = new SupplierProductManage();
        public IPurchaseOrderManage PurchaseOrderManageBz = new PurchaseOrderManage();
        public IProductManage ProductManageBz = new ProductManage();
        public SupplierManage SupplierManageBz = new SupplierManage();
        // GET: Layer
        [AllowAnonymous]
        public ActionResult ProductList(string SupplierName,string filter, int p = 1, string searchFild = "")
        {
            var arr = filter.Split('|');
            ViewBag.filter = filter;
            var supplierModel = SupplierManageBz.Get(o => o.CorpName == SupplierName);
            if (supplierModel != null) {
                int SupplierId = supplierModel.ID;
                var model = SupplierProductManageBz.Query(
                               SupplierProductManageBz.LoadAll(o => o.SupplierId == SupplierId && !arr.Contains(o.ProductName) && o.ProductName.Contains(searchFild)).OrderByDescending(o => o.ProductId),
                               p,
                               10);
                ViewBag.searchFild = searchFild;
                return View(model);
            }
            else
            {
                return  View();
            }
        }
        /// <summary>
        /// 产品库存
        /// </summary>
        /// <param name="SupplierName"></param>
        /// <param name="filter"></param>
        /// <param name="p"></param>
        /// <param name="searchFild"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult ProductStockList(string filter, int p = 1, string searchFild = "")
        {
            var arr = filter.Split('|');
            ViewBag.filter = filter;

            var model = ProductManageBz.Query(
                            ProductManageBz.LoadAll(o=>!arr.Contains(o.ProductName) && o.ProductName.Contains(searchFild)).OrderByDescending(o => o.ProductId),
                            p,
                            10);
            ViewBag.searchFild = searchFild;
            return View(model);
        }
        [AllowAnonymous]
        public ActionResult PurchaseOrderListForAccept(string searchFild = "", int p = 1)
        {
                var model = PurchaseOrderManageBz.Query(
                               PurchaseOrderManageBz.LoadAll(o => (o.Status==OrderStatus.待验收 || o.Status == OrderStatus.部分验收) && o.PurchaseOrderNo.Contains(searchFild)).OrderByDescending(o => o.ID),
                               p,
                               10);
                ViewBag.searchFild = searchFild;
                return View(model);
        }
    }
}

ProductionManageSys/ProductionManage/Views/AcceptOrder/AcceptDetail.cshtml
@using Service.Model;
@using ProductionManage.Controllers;
@model AcceptOrderView
@{
    var viewName = "Index";
}
<style>
    .theme-black .tpl-table-black tbody > tr > td {
        border: 0;
    }
</style>
@using (Html.BeginForm("Save", "AcceptOrder", FormMethod.Post, new { @class = "am-form tpl-form-line-form" }))
{
    <div class="row">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
            <div class="widget am-cf">
                <div class="widget-head am-cf">
                    <div class="widget-title am-fl">单头</div>
                    <div class="widget-function am-fr">

                    </div>
                </div>
                <div class="widget-body am-fr">
                    <div style="padding:5px">
                        <div class="am-form-group">
                            @Html.HiddenFor(o => o.ID)
                            <label for="user-name" class="am-u-sm-1 am-form-label ">验收单号</label>
                            <div class="am-u-sm-3">
                                @Html.TextBoxFor(o => (o.AcceptOrderNo), new { @class = "tpl-form-inpu", placeholder = "", @readonly = "true" })
                            </div>
                            <label for="user-name" class="am-u-sm-1 am-form-label ">采购单号</label>
                            <div class="am-u-sm-3">
                                @Html.TextBoxFor(o => (o.PurchaseOrderNo), new { @class = "tpl-form-inpu", placeholder = "", @readonly = "true" })
                            </div>
                            <label for="user-name" class="am-u-sm-1 am-form-label">验收日期</label>
                            <div class="am-u-sm-3">
                                @Html.TextBoxFor(o => (o.AcceptDate), new { @class = "tpl-form-inpu", placeholder = "", @readonly = "true" })
                            </div>
                        </div>
                        <div class="am-form-group">
                            <label for="user-name" class="am-u-sm-1 am-form-label">总金额</label>
                            <div class="am-u-sm-3">
                                @Html.TextBoxFor(o => o.SumPrice, new { @class = "", placeholder = "", disabled = "disabled" })
                            </div>
                            <label for="user-name" class="am-u-sm-1 am-form-label">备注</label>
                            <div class="am-u-sm-7">
                                @Html.TextBoxFor(o => o.Remark, new { @class = "tpl-form-input", placeholder = "" })
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
            <div class="widget am-cf">
                <div class="widget-head am-cf">
                    <div class="widget-title am-fl">单身</div>

                </div>
                <div class="widget-body am-fr">

                    <div class="am-u-sm-12">
                        <table class="am-table am-table-compact  tpl-table-black " id="tb">
                            <thead>
                                <tr>

                                    <th>产品名称</th>
                                    <th>单价</th>
                                    <th>采购数量</th>
                                    <th>待验收数</th>
                                    <th>验收数</th>
                                    <th>验收总金额</th>
                                    <th>备注</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model?.AcceptOrderDetailView != null)
                                {
                                    for (int i = 0; i < Model.AcceptOrderDetailView.Count; i++)
                                    {
                                        <tr class="odd gradeX">
                                            @Html.HiddenFor(o => Model.AcceptOrderDetailView[i].ProductId)
                                            <td>@Html.TextBoxFor(o => Model.AcceptOrderDetailView[i].ProductName, new Dictionary<string, object> { { "class", "tpl-form-input" }, { "placeholder", "" }, { "readonly", "true" } })</td>
                                            <td>@Html.TextBoxFor(o => Model.AcceptOrderDetailView[i].Price, new Dictionary<string, object> { { "class", "tpl-form-input" }, { "placeholder", "" }, { "readonly", "true" } })</td>
                                            <td>@Html.TextBoxFor(o => Model.AcceptOrderDetailView[i].PurchaseNum, new Dictionary<string, object> { { "class", "tpl-form-input" }, { "placeholder", "" }, { "readonly", "true" } })</td>
                                            <td>@Html.TextBoxFor(o => Model.AcceptOrderDetailView[i].PurchaseNumWait, new Dictionary<string, object> { { "class", "tpl-form-input" }, { "placeholder", "" }, { "readonly", "true" } })</td>
                                            <td>@Html.TextBoxFor(o => Model.AcceptOrderDetailView[i].AcceptNum, new Dictionary<string, object> { { "class", "tpl-form-input" }, { "placeholder", "" }, { "readonly", "true" } })</td>
                                            <td>@Html.TextBoxFor(o => Model.AcceptOrderDetailView[i].SumPrice, new Dictionary<string, object> { { "class", "tpl-form-input" }, { "placeholder", "" }, { "readonly", "true" } })</td>
                                            <td>@Html.TextBoxFor(o => Model.AcceptOrderDetailView[i].Remark, new Dictionary<string, object> { { "class", "tpl-form-input" }, { "placeholder", "" }, { "readonly", "true" } })</td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
        <div class="am-form-group">
            <div class="am-u-sm-7 am-u-sm-push-5">
                <button type="button" class="am-btn am-btn-primary tpl-btn-bg-color-success " onclick="location.href='@Url.Action("Index")'">返回</button>
            </div>
        </div>
        <input type="hidden" id="hiddenProducts" />
    </div>
}
<script type="text/javascript">
      $(function(){
          if("@ViewBag.Msg"!="")
              layer.msg("@ViewBag.Msg");


      });
    function AddRow(row) {

        var length = $("#tb tbody tr").length;

        var data="<tr class=\"odd gradeX\">"
        data += "<input id=\"AcceptOrderDetailView_" + length + "__ProductId\" name=\"AcceptOrderDetailView[" + length + "].ProductId\" type=\"hidden\" value=\"" + row.ProductId + "\">"
        data += "<td><input class=\"tpl-form-input\" id=\"AcceptOrderDetailView_" + length + "__ProductName\" name=\"AcceptOrderDetailView[" + length + "].ProductName\" placeholder=\"\" readonly=\"true\" type=\"text\" value=\"" + row.ProductName + "\"></td>"
        data += "<td><input class=\"tpl-form-input\" id=\"AcceptOrderDetailView_" + length + "__Price\" name=\"AcceptOrderDetailView[" + length + "].Price\" placeholder=\"\" readonly=\"true\" type=\"text\" value=\"" + row.Price + "\"></td>"
        data += "<td><input class=\"tpl-form-input\" id=\"AcceptOrderDetailView_" + length + "__PurchaseNum\" name=\"AcceptOrderDetailView[" + length + "].PurchaseNum\" placeholder=\"\" readonly=\"true\" type=\"text\" value=\"" + row.PurchaseNum + "\"></td>"
        data += "<td><input class=\"tpl-form-input\" data-val=\"true\" data-val-number=\"字段 PurchaseNumWait 必须是一个数字。\" data-val-required=\"PurchaseNumWait 字段是必需的。\" id=\"AcceptOrderDetailView_" + length + "__PurchaseNumWait\" name=\"AcceptOrderDetailView[" + length + "].PurchaseNumWait\" placeholder=\"\" readonly=\"true\" type=\"text\" value=\"" + row.PurchaseNumWait + "\"></td>"
        data += "<td><input class=\"input_number\" id=\"AcceptOrderDetailView_" + length + "__AcceptNum\" name=\"AcceptOrderDetailView[" + length + "].AcceptNum\" onkeyup=\"ValidNum(this,true);Cal(this)\" placeholder=\"请输入数量\" type=\"text\" value=\"\"></td>"
        data += "<td><input class=\"tpl-form-input\" id=\"AcceptOrderDetailView_" + length + "__SumPrice\" name=\"AcceptOrderDetailView[" + length + "].SumPrice\" onkeyup=\"ValidNum(this);\" placeholder=\"\" readonly=\"true\" type=\"text\" value=\"0\"></td>"
        data += "<td><input class=\"tpl-form-input\" id=\"AcceptOrderDetailView_" + length + "__Remark\" name=\"AcceptOrderDetailView[" + length + "].Remark\" placeholder=\"请输入备注\" type=\"text\" value=\"\"></td>"
        data += "</tr>"
        $("#tb tbody").append(data);
    }
    function Cal(obj) {
        var num = $(obj).val();
        if (num == "") {
            num = 0;
        }
        var PurchaseNumWait = $(obj).parents("tr").find("[name*='PurchaseNumWait']").val();
        if (parseInt(num) > parseInt(PurchaseNumWait)) {
            str = num.substring(0, num.length - 1)
            $(obj).val(str);
            return;
        }

        var PurchaseOrderDetail_Price = $(obj).parents("tr").find("[name*='Price']").val();

        console.log(PurchaseOrderDetail_Price);
        $(obj).parents("tr").find("[name*='SumPrice']").val(Math.round(parseInt(num) * parseFloat(PurchaseOrderDetail_Price)*100)/100);
        CalAll();
    }
    function CalAll() {
        var sum = 0;
        $.each($("#tb tbody tr"), function (index, data) {
            var PurchaseOrderDetail_Price = $(data).find("[name*='Price']").val();
            var PurchaseOrderDetail_PurchaseNum = $(data).find("[name*='AcceptNum']").val();
            if (PurchaseOrderDetail_PurchaseNum == "") {
                PurchaseOrderDetail_PurchaseNum = 0;
            }
            sum = Math.round((sum + parseFloat(PurchaseOrderDetail_Price) * parseInt(PurchaseOrderDetail_PurchaseNum))* 100)  / 100;
        });
        $("#SumPrice").val(sum);
    }
    function openWin() {

        layer.open({
            type: 2,
            title: '选择采购单',
            shadeClose: true,
            id: "main",
            shade: true,
            offset: '100px',
            shade: 0.8,
            area: '80%',
            content: ['@Url.Action("PurchaseOrderListForAccept", "Layer")', 'no'],
            end: function () {
                var hiddenProdcuts = $("#hiddenProducts").val();
                if (hiddenProdcuts == "") return;
                $("#hiddenProducts").val("");
                var data = JSON.parse(hiddenProdcuts);
                $("#tb tbody").html("");
                $.each(data, function (index, row) {
                    AddRow(row);
                });
                $("#SumPrice").val("0");


            }
        });
    }
</script>

ProductionManageSys/ProductionManage/Views/AcceptOrder/Index.cshtml
@using Domain.Model;
@using Common;

@model PageInfo<AcceptOrder>
@{
    var viewName = "Index";
    var rowStyle = "odd gradeX";
}
<div class="row">

    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
        <div class="widget am-cf">
            <div class="widget-head am-cf">
                <div class="widget-title am-fl">验收单</div>
                <div class="widget-function am-fr">
                    <a href="javascript:;" class="am-icon-cog"></a>
                </div>
            </div>
            <div class="widget-body  am-fr">
                <div class="am-u-sm-12 am-u-md-6 am-u-lg-6">
                    <div class="am-form-group">
                        <div class="am-btn-toolbar">
                            <div class="am-btn-group am-btn-group-xs">
                                <button type="button" data-role="Edit" class="am-btn am-btn-default am-btn-success" onclick="location.href='@Url.Action("AcceptAdd")'"><span class="am-icon-plus"></span> 新增</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="am-u-sm-12 am-u-md-6 am-u-lg-6">
                    <div class="am-form-group">
                        <div class="am-btn-toolbar">
                            <div class="am-btn-group am-btn-group-xs">
                                @*  <button type="button" class="am-btn am-btn-default am-btn-success" onclick="location.href='@Url.Action("ApplyJobAdd")'"><span class="am-icon-plus"></span> 新增</button>*@
                            </div>
                        </div>
                    </div>
                </div>
                <div class="am-u-sm-12 am-u-md-12 am-u-lg-3">
                    <div class="am-input-group am-input-group-sm tpl-form-border-form cl-p">
                        <input class="am-form-field " type="text" id="txt_search" placeholder="请输入验收单号...">
                        <span class="am-input-group-btn">
                            <button class="am-btn  am-btn-default am-btn-success tpl-table-list-field am-icon-search" onclick="Search()" type="button"></button>
                        </span>
                    </div>
                </div>
                <div class="am-u-sm-12">
                    <table class="am-table am-table-compact am-table-striped tpl-table-black " id="tb" width="100%">
                        <thead>
                            <tr>
                                <th>验收单号</th>
                                <th>采购单号</th>
                                <th>验收总数量</th>
                                <th>验收总金额</th>
                                <th>状态</th>
                                <th>备注</th>
                                <th>验收时间</th>
                                <th>验收人</th>
                                <th>最后操作人</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var row in Model.List)
                            {
                                <tr class=@rowStyle>
                                    <td>@row.AcceptOrderNo</td>
                                    <td>@row.PurchaseOrderNo</td>
                                    <td>@row.AcceptNum</td>
                                    <td>@row.SumPrice</td>
                                    <td>@row.Status</td>
                                    <td>@row.Remark</td>
                                    <td>@row.AcceptDate</td>
                                    <td>@row.Accepter</td>
                                    <td>@row.Oper</td>
                                    <td>
                                        <div class="tpl-table-black-operation">
                                            <a href=@Url.Action("AcceptDetail",  new { AcceptOrderNo = row.AcceptOrderNo })>
                                                <i class="am-icon-pencil"></i> 详情
                                            </a>
                                            <a data-role="Edit" href=@Url.Action("AcceptEidt", new { AcceptOrderNo = row.AcceptOrderNo }) class="tpl-table-black-operation-del">
                                                <i class="am-icon-trash"></i> 编辑
                                            </a>
                                            <a data-role="Delete" href=@Url.Action("AcceptDel", new { id=row.ID}) class="tpl-table-black-operation-del">
                                                <i class="am-icon-trash"></i> 删除
                                            </a>
                                            <a data-role="Approve" href=@Url.Action("AcceptApprove", new { id=row.ID}) class="tpl-table-black-operation-del">
                                                <i class="am-icon-trash"></i> 审批
                                            </a>
                                            @*<a data-role="Reject" href=@Url.Action("AcceptReject", new { id=row.ID}) class="tpl-table-black-operation-del">
                                                <i class="am-icon-trash"></i> 驳回
                                            </a>*@
                                        </div>
                                    </td>
                                </tr>
                                rowStyle = "even gradeC";
                            }
                        </tbody>
                    </table>
                </div>
                <div class="am-u-lg-12 am-cf">
                    <div class="am-fr">
                        <ul class="am-pagination tpl-pagination">
                            <li>
                                <a href=@Url.Action(viewName, new { p = 1,searchFild=ViewBag.searchFild })>«</a>
                            </li>
                            @for (int i = Model.Index - 4; i < Model.Index; i++)
                            {
                                if (i > 0)
                                {
                                    <li><a href=@Url.Action(viewName, new { p = i,searchFild=ViewBag.searchFild  })>@i</a></li>
                                }
                            }
                            <li class="am-active"><a href="#">@Model.Index</a></li>
                            @for (int i = 1; i <= 5; i++)
                            {
                                if (Model.Index + i <= Math.Ceiling((decimal)Model.Count / Model.PageSize))
                                {
                                    <li><a href=@Url.Action(viewName, new { p = Model.Index + i,searchFild=ViewBag.searchFild  })>@(@Model.Index + @i)</a></li>
                                }
                            }
                            <li>
                                <a href=@Url.Action(viewName, new { p = Math.Ceiling((decimal)Model.Count / Model.PageSize),searchFild=ViewBag.searchFild  })>»</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
      $(function(){
          if("@TempData["Msg"]"!="")
              layer.msg("@TempData["Msg"]");
       });
</script>
<script src="~/scripts/amazeui.datatables.min.js"></script>

@section scripts{

    function Search(){

    var value = $("#txt_search").val();

    location.href='@Url.Action("Index")'+'?searchFild='+value;

    }

}