ProductionManageSys/ProductionManage/Controllers/LayerController.cs
using ProductionManage.Models;
using Service.IService;
using Service.ServiceImp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionManage.Controllers
{
    public class LayerController : BaseController
    {
        public ISupplierProductManage SupplierProductManageBz = new SupplierProductManage();
        public IPurchaseOrderManage PurchaseOrderManageBz = new PurchaseOrderManage();
        public IProductManage ProductManageBz = new ProductManage();
        public SupplierManage SupplierManageBz = new SupplierManage();
        // GET: Layer
        [AllowAnonymous]
        public ActionResult ProductList(string SupplierName,string filter, int p = 1, string searchFild = "")
        {
            var arr = filter.Split('|');
            ViewBag.filter = filter;
            var supplierModel = SupplierManageBz.Get(o => o.CorpName == SupplierName);
            if (supplierModel != null) {
                int SupplierId = supplierModel.ID;
                var model = SupplierProductManageBz.Query(
                               SupplierProductManageBz.LoadAll(o => o.SupplierId == SupplierId && !arr.Contains(o.ProductName) && o.ProductName.Contains(searchFild)).OrderByDescending(o => o.ProductId),
                               p,
                               10);
                ViewBag.searchFild = searchFild;
                return View(model);
            }
            else
            {
                return  View();
            }
        }
        /// <summary>
        /// 产品库存
        /// </summary>
        /// <param name="SupplierName"></param>
        /// <param name="filter"></param>
        /// <param name="p"></param>
        /// <param name="searchFild"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult ProductStockList(string filter, int p = 1, string searchFild = "")
        {
            var arr = filter.Split('|');
            ViewBag.filter = filter;

            var model = ProductManageBz.Query(
                            ProductManageBz.LoadAll(o=>!arr.Contains(o.ProductName) && o.ProductName.Contains(searchFild)).OrderByDescending(o => o.ProductId),
                            p,
                            10);
            ViewBag.searchFild = searchFild;
            return View(model);
        }
        [AllowAnonymous]
        public ActionResult PurchaseOrderListForAccept(string searchFild = "", int p = 1)
        {
                var model = PurchaseOrderManageBz.Query(
                               PurchaseOrderManageBz.LoadAll(o => (o.Status==OrderStatus.待验收 || o.Status == OrderStatus.部分验收) && o.PurchaseOrderNo.Contains(searchFild)).OrderByDescending(o => o.ID),
                               p,
                               10);
                ViewBag.searchFild = searchFild;
                return View(model);
        }
    }
}

ProductionManageSys/ProductionManage/Controllers/ProductPutOutOrderController.cs
using Domain.Model;
using ProductionManage.Models;
using Service;
using Service.IService;
using Service.ServiceImp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionManage.Controllers
{
    public class ProductPutOutOrderController : BaseController
    {
        public IProductManage ProductManageBz = new ProductManage();
        public IProductPutOutOrderManage ProductPutOutOrderManageBz = new ProductPutOutOrderManage ();
        public IProductLogManage ProductLogManageBz = new ProductLogManage();
        //入库
        public ActionResult PutIndex(int p = 1, string searchFild = "")
        {
            var model = ProductPutOutOrderManageBz.Query(
                           ProductPutOutOrderManageBz.LoadAll(o => o.Type=="入库" && o.ProductOrderNo.Contains(searchFild)).OrderByDescending(o => o.ID),
                           p,
                           10);
            ViewBag.searchFild = searchFild;
            return View(model);
        }
        public ActionResult PutDetail(string ProductOrderNo = "")
        {
            var model = ProductPutOutOrderManageBz.Get(o => o.ProductOrderNo == ProductOrderNo);
            return View(model);
        }
        public ActionResult PutEidt(string ProductOrderNo = "",string msg="")
        {
            var model = ProductPutOutOrderManageBz.Get(o=>o.ProductOrderNo == ProductOrderNo);
            ViewBag.Msg = msg;
            return View(model);
        }

        public ActionResult PutOrderApprove(int id)
        {
            var uow = new UnitOfWork();
            ProductManageBz.SetUOW(uow);
            ProductPutOutOrderManageBz.SetUOW(uow);
            ProductLogManageBz.SetUOW(uow);

            var model = ProductPutOutOrderManageBz.Get(o => o.ID == id);
            if (model.Status != OrderStatus.未审批)
            {
                TempData["Msg"] = "此订单非未审批状态，无法审批！";
            }
            else
            {
                foreach(var detail in model.ProductOrderDetail)
                {
                    var product = ProductManageBz.Get(o => o.ProductName == detail.ProductName);
                    if (product == null)//add
                    {
                        ProductManageBz.Save(new Product
                        {
                            From = "入库",
                            Location = "",
                            Price = detail.Price,
                            Type = "物料",
                            ProductName=detail.ProductName,
                            LockNum=0,
                            Remark="",
                            SumNum=detail.Num
                        },false);
                    }
                    else
                    {
                        product.SumNum += detail.Num;
                        ProductManageBz.Update(product,false);
                    }
                }
                //库存记录(验收产品种类一般不多故分开结构清晰)
                foreach (var row in model.ProductOrderDetail)
                {
                    if (row.Num > 0)
                    {
                        ProductLogManageBz.Save(new ProductLog
                        {
                            In1Out = "In",
                            Oper = CurrentUser.UserName,
                            OperTime = DateTime.Now,
                            num = row.Num,
                            ProductName = row.ProductName,
                            Remark = $"入库单号:{model.ProductOrderNo}审批入库"
                        }, false);
                    }
                }
                model.Status = OrderStatus.已审批;
                model.Oper = CurrentUser.UserName;
                var isSuccess = ProductPutOutOrderManageBz.Update(model);
                if (isSuccess)
                {
                    TempData["Msg"] = "审批成功！";
                }
                else
                {
                    TempData["Msg"] = "审批失败！";
                }
            }
            return RedirectToAction("PutIndex");
        }
        public ActionResult PutOrderReject(int id)
        {
            var uow = new UnitOfWork();
            ProductManageBz.SetUOW(uow);
            ProductPutOutOrderManageBz.SetUOW(uow);
            ProductLogManageBz.SetUOW(uow);

            var model = ProductPutOutOrderManageBz.Get(o => o.ID == id);
            if (model.Status != OrderStatus.已审批)
            {
                TempData["Msg"] = "此订单非已审批状态，无法驳回！";
            }
            else
            {
                foreach (var detail in model.ProductOrderDetail)
                {
                    var product = ProductManageBz.Get(o => o.ProductName == detail.ProductName);
                    if (product == null || product.SumNum<detail.Num)//add
                    {
                        TempData["Msg"] = "库存数量不足，无法驳回！";
                        return RedirectToAction("PutIndex");
                    }
                    else
                    {
                        product.SumNum -= detail.Num;
                        ProductManageBz.Update(product, false);
                    }
                }
                //库存记录(验收产品种类一般不多故分开结构清晰)
                foreach (var row in model.ProductOrderDetail)
                {
                    if (row.Num > 0)
                    {
                        ProductLogManageBz.Save(new ProductLog
                        {
                            In1Out = "Out",
                            Oper = CurrentUser.UserName,
                            OperTime = DateTime.Now,
                            num = row.Num,
                            ProductName = row.ProductName,
                            Remark = $"入库单号:{model.ProductOrderNo}驳回入库"
                        }, false);
                    }
                }
                model.Status = OrderStatus.未审批;
                model.Oper = CurrentUser.UserName;
                var isSuccess = ProductPutOutOrderManageBz.Update(model);
                if (isSuccess)
                {
                    TempData["Msg"] = "驳回成功！";
                }
                else
                {
                    TempData["Msg"] = "驳回失败！";
                }
            }
            return RedirectToAction("PutIndex");
        }


        public ActionResult PutOrderDel(int id)
        {
            var model = ProductPutOutOrderManageBz.Get(o => o.ID == id);
            if (model.Status != OrderStatus.未审批)
            {
                TempData["Msg"] = "此订单非未审批状态，无法删除！";
            }
            else
            {
                var isSuccess = ProductPutOutOrderManageBz.Delete(o => o.ID == id);
                if (isSuccess)
                {
                    TempData["Msg"] = "删除成功！";
                }
                else
                {
                    TempData["Msg"] = "删除失败！";
                }
            }

            return RedirectToAction("PutIndex");
        }
        public ActionResult PutSave(ProductPutOutOrder model)
        {
            try
            {
                var ProductOrderNo = model.ProductOrderNo ?? "";
                //验证
               
                if (model.ProductPutOrderDate<new DateTime(2017,1,1))
                {
                    ViewBag.Msg = "请选择订单日期";
                    return View("PutEidt", model);
                }

                model.ProductOrderDetail = model.ProductOrderDetail?.Where(o => o.ProductName != null && o.ProductName != "").ToList();
                if (model.ProductOrderDetail == null || !model.ProductOrderDetail.Any())
                {
                    ViewBag.Msg = "请添加入库产品";
                    return View("PutEidt", model);
                }

                if (string.IsNullOrWhiteSpace(ProductOrderNo))//新增
                {
                    model.ProductOrderNo = Common.Utils.GetOrderNumber();
                    while (ProductPutOutOrderManageBz.IsExist(o => o.ProductOrderNo == model.ProductOrderNo))
                    {
                        model.ProductOrderNo = Common.Utils.GetOrderNumber();
                    }
                    model.Oper = CurrentUser.UserName;
                    model.Status = OrderStatus.未审批;
                    float sumPriceTotal = 0;
                    int sumNumTotal = 0;
                    foreach (var detail in model.ProductOrderDetail)
                    {
                        float price = detail.Price;
                        int num = detail.Num;
                        float sumprice = price * (num);
                        sumPriceTotal += sumprice;
                        sumNumTotal += (num);
                        detail.SumPrice = sumprice;
                    }
                    model.SumPrice = sumPriceTotal;
                    model.SumNum = sumNumTotal;
                    model.Type = "入库";

                    bool isSuccess = ProductPutOutOrderManageBz.Save(model);
                    ViewBag.Msg = isSuccess ? "保存成功！" : "保存失败！";

                }
                else
                {
                    var oldData = ProductPutOutOrderManageBz.Get(o => o.ProductOrderNo == model.ProductOrderNo);
                    var newData = Common.Tools.CopyObjectValue(oldData, model);
                    newData.ProductOrderDetail.ForEach(o => o.ProductPutOutOrderId = newData.ID);

                    newData.Status = OrderStatus.未审批;
                    float sumPriceTotal = 0;
                    int sumNumTotal = 0;
                    foreach (var detail in newData.ProductOrderDetail)
                    {
                        float price = detail.Price;
                        int num = detail.Num;
                        float sumprice = price * num;

                        sumPriceTotal += sumprice;
                        sumNumTotal += num;
                        detail.SumPrice = sumprice;
                    }
                    newData.SumPrice = sumPriceTotal;

ProductionManageSys/ProductionManage/Views/ProductPutOutOrder/OutDetail.cshtml
@using Domain.Model;
@using ProductionManage.Controllers;
@model ProductPutOutOrder
@{
    var viewName = "Index";
}
<style>
    .theme-black .tpl-table-black tbody > tr > td {
        border: 0;
    }
</style>
@using (Html.BeginForm("Save", "ProductPutOutOrder", FormMethod.Post, new { @class = "am-form tpl-form-line-form" }))
{
    <div class="row">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
            <div class="widget am-cf">
                <div class="widget-head am-cf">
                    <div class="widget-title am-fl">单头</div>
                    <div class="widget-function am-fr">

                    </div>
                </div>
                <div class="widget-body am-fr">
                    <div style="padding:5px">
                        <div class="am-form-group">
                            @Html.HiddenFor(o => o.ID)
                            <label for="user-name" class="am-u-sm-1 am-form-label ">出库单号</label>
                            <div class="am-u-sm-4">
                                @Html.TextBoxFor(o => (o.ProductOrderNo), new { @class = "tpl-form-inpu", placeholder = "", @readonly = "true" })
                            </div>
                            <label for="user-name" class="am-u-sm-2 am-form-label">总金额</label>
                            <div class="am-u-sm-5">
                                @Html.TextBoxFor(o => o.SumPrice, new { @class = "", placeholder = "", disabled = "disabled" })
                            </div>
                        </div>
                        <div class="am-form-group">
                            <label for="user-name" class="am-u-sm-1 am-form-label">订单日期</label>
                            <div class="am-u-sm-4">
                                @Html.TextBoxFor(o => o.ProductPutOrderDate, new Dictionary<string, object> { { "class", "am-form-field tpl-form-no-bg am-margin-top-xs" }, { "placeholder", "请选择订单日期" }, { "data-am-datepicker", "" }, { "readonly", "true" }, { "style", "cursor:default" } })
                            </div>
                            <label for="user-name" class="am-u-sm-2 am-form-label">摘要</label>
                            <div class="am-u-sm-5">
                                @Html.TextBoxFor(o => o.Content, new { @class = "tpl-form-input", placeholder = "请输入摘要" })
                            </div>
                        </div>
                        <div class="am-form-group">
                            <label for="user-name" class="am-u-sm-1 am-form-label">备注</label>
                            <div class="am-u-sm-11">
                                @Html.TextBoxFor(o => o.Remark, new { @class = "tpl-form-input", placeholder = "请输入备注" })
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
            <div class="widget am-cf">
                <div class="widget-head am-cf">
                    <div class="widget-title am-fl">单身</div>

                </div>
                <div class="widget-body am-fr">

                    <div class="am-u-sm-12">
                        <table class="am-table am-table-compact  tpl-table-black " id="tb">
                            <thead>
                                <tr>

                                    <th>产品名称</th>
                                    <th>单价</th>
                                    <th>数量</th>
                                    <th>总金额</th>
                                    <th>备注</th>

                                </tr>
                            </thead>
                            <tbody>
                                @if (Model?.ProductOrderDetail != null)
                                {
                                    for (int i = 0; i < Model.ProductOrderDetail.Count; i++)
                                    {
                                        <tr class="odd gradeX">
                                            <td>@Html.TextBoxFor(o => Model.ProductOrderDetail[i].ProductName, new { @class = "tpl-form-input", placeholder = "请选择产品" })</td>
                                            <td>@Html.TextBoxFor(o => Model.ProductOrderDetail[i].Price, new Dictionary<string, object> { { "class", "tpl-form-input" }, { "placeholder", "" }, { "onkeyup", "ValidNum(this);Cal(this)" } })</td>
                                            <td>@Html.TextBoxFor(o => Model.ProductOrderDetail[i].Num, new { @class = "input_number", placeholder = "请输入数量", onkeyup = "ValidNum(this,true);Cal(this)" })</td>
                                            <td>@Html.TextBoxFor(o => Model.ProductOrderDetail[i].SumPrice, new Dictionary<string, object> { { "class", "tpl-form-input" }, { "placeholder", "" }, { "onkeyup", "ValidNum(this);" }, { "readonly", "true" } })</td>
                                            <td>@Html.TextBoxFor(o => Model.ProductOrderDetail[i].Remark, new { @class = "tpl-form-input", placeholder = "请输入备注" })</td>

                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
        <div class="am-form-group">
            <div class="am-u-sm-7 am-u-sm-push-5">

                <button type="button" class="am-btn am-btn-primary tpl-btn-bg-color-success " onclick="location.href='@Url.Action("PutIndex")'">返回</button>
            </div>
        </div>
        <input type="hidden" id="hiddenProducts" />
    </div>
}
<script type="text/javascript">
      $(function(){
          if("@ViewBag.Msg"!="")
              layer.msg("@ViewBag.Msg");


      });
    function AddRow() {
        var length = $("#tb tbody tr").length;
        var data="<tr class=\"odd gradeX\">";
        data += "<td><input class=\"tpl-form-input\" id=\"ProductOrderDetail_" + length + "__ProductName\" name=\"ProductOrderDetail[" + length + "].ProductName\" placeholder=\"请选择产品\" readonly=\"true\" type=\"text\" value=\"\"></td>";
        data += "<td><input class=\"tpl-form-input\" data-val=\"true\" data-val-number=\"字段 Price 必须是一个数字。\" data-val-required=\"Price 字段是必需的。\" id=\"ProductOrderDetail_" + length + "__Price\" name=\"ProductOrderDetail[" + length + "].Price\" onkeyup=\"ValidNum(this);Cal(this)\" placeholder=\"\" type=\"text\" value=\"\"></td>";
        data += "<td><input class=\"input_number\" data-val=\"true\" data-val-number=\"字段 Num 必须是一个数字。\" data-val-required=\"Num 字段是必需的。\" id=\"ProductOrderDetail_" + length + "__Num\" name=\"ProductOrderDetail[" + length + "].Num\" onkeyup=\"ValidNum(this,true);Cal(this)\" placeholder=\"请输入数量\" type=\"text\" value=\"\"></td>";
        data += "<td><input class=\"tpl-form-input\" data-val=\"true\" data-val-number=\"字段 SumPrice 必须是一个数字。\" data-val-required=\"SumPrice 字段是必需的。\" id=\"ProductOrderDetail_" + length + "__SumPrice\" name=\"ProductOrderDetail[" + length + "].SumPrice\" onkeyup=\"ValidNum(this);\" placeholder=\"\" readonly=\"true\" type=\"text\" value=\"\"></td>";
        data += "<td><input class=\"tpl-form-input\" id=\"ProductOrderDetail_" + length + "__Remark\" name=\"ProductOrderDetail[" + length + "].Remark\" placeholder=\"请输入备注\" type=\"text\" value=\"\"></td>";
        data+="<td>";
        data+="<div class=\"tpl-table-black-operation\">";
        data+="<a href=\"#\" class=\"tpl-table-black-operation-del\" onclick=\"openWin(this)\">";
        data+="<i class=\"am-icon-trash\"></i> 选择";
        data+="</a>";
        data+="<a href=\"#\" class=\"tpl-table-black-operation-del\" onclick=\"DelRow(this)\">";
        data+="<i class=\"am-icon-trash\"></i> 删除";
        data+="</a>";
        data+="</div>";
        data+="</td>";
        data+="</tr>";
        $("#tb tbody").append(data);
    }
    function DelRow(obj) {
        $(obj).parents("tr").find("[name*='ProductName']").val("");
        $(obj).parents("tr").find("[name*='Price']").val("0");
        $(obj).parents("tr").attr("style","display:none");
        CalAll();
    }
    function Cal(obj) {
        var num = $(obj).parents("tr").find("[name*='Num']").val();
        var PurchaseOrderDetail_Price = $(obj).parents("tr").find("[name*='Price']").val();

        $(obj).parents("tr").find("[name*='SumPrice']").val(Math.round(parseInt(num) * parseFloat(PurchaseOrderDetail_Price)*100)/100);
        CalAll();
    }
    function CalAll() {
        var sum = 0;
        $.each($("#tb tbody tr"), function (index, data) {
            var PurchaseOrderDetail_Price = $(data).find("[name*='Price']").val();
            var PurchaseOrderDetail_PurchaseNum = $(data).find("[name*='Num']").val();

            sum = Math.round((sum + parseFloat(PurchaseOrderDetail_Price) * parseInt(PurchaseOrderDetail_PurchaseNum))* 100)  / 100;
        });
        $("#SumPrice").val(sum);
    }
    function openWin(obj) {
        var productNameArr = $("#tb tbody tr").find("[name*='ProductName']");
        var filter = "";
        $.each(productNameArr, function (index, data) {
            filter += $(data).val() + "|";
        });
        layer.open({
            type: 2,
            title: '选择产品',
            shadeClose: true,
            id: "main",
            shade: true,
            offset: '100px',
            shade: 0.8,
            area: '80%',
            content: ['@Url.Action("ProductStockList", "Layer")' + "?SupplierName=''&filter=" + filter, 'no'],
            end: function () {

                var hiddenProdcuts = $("#hiddenProducts").val();
                if (hiddenProdcuts == "") return;
                $("#hiddenProducts").val("");
                var data = JSON.parse(hiddenProdcuts);

                $(obj).parents("tr").find("[name*='ProductName']").val(data.ProductName).attr("readonly","true");
                $(obj).parents("tr").find("[name*='Price']").val(data.Price).attr("readonly", "true");;

                CalAll();
            }
        });
    }
</script>

ProductionManageSys/ProductionManage/Views/ProductPutOutOrder/OutIndex.cshtml
@using Domain.Model;
@using Common;

@model PageInfo<ProductPutOutOrder>
@{
    var viewName = "Index";
    var rowStyle = "odd gradeX";
}
<div class="row">

    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
        <div class="widget am-cf">
            <div class="widget-head am-cf">
                <div class="widget-title am-fl">出库单</div>
                <div class="widget-function am-fr">
                    <a href="javascript:;" class="am-icon-cog"></a>
                </div>
            </div>
            <div class="widget-body  am-fr">
                <div class="am-u-sm-12 am-u-md-6 am-u-lg-6">
                    <div class="am-form-group">
                        <div class="am-btn-toolbar">
                            <div class="am-btn-group am-btn-group-xs">
                                <button type="button" data-role="Edit" class="am-btn am-btn-default am-btn-success" onclick="location.href='@Url.Action("OutEidt")'"><span class="am-icon-plus"></span> 新增</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="am-u-sm-12 am-u-md-6 am-u-lg-6">
                    <div class="am-form-group">
                        <div class="am-btn-toolbar">
                            <div class="am-btn-group am-btn-group-xs">
                                @*  <button type="button" class="am-btn am-btn-default am-btn-success" onclick="location.href='@Url.Action("ApplyJobAdd")'"><span class="am-icon-plus"></span> 新增</button>*@
                            </div>
                        </div>
                    </div>
                </div>
                <div class="am-u-sm-12 am-u-md-12 am-u-lg-3">
                    <div class="am-input-group am-input-group-sm tpl-form-border-form cl-p">
                        <input class="am-form-field " type="text" id="txt_search" placeholder="请输入出库单号...">
                        <span class="am-input-group-btn">
                            <button class="am-btn  am-btn-default am-btn-success tpl-table-list-field am-icon-search" onclick="Search()" type="button"></button>
                        </span>
                    </div>
                </div>
                <div class="am-u-sm-12">
                    <table class="am-table am-table-compact am-table-striped tpl-table-black " id="tb" width="100%">
                        <thead>
                            <tr>

                                <th>出库单号</th>
                                <th>订单日期</th>
                                <th>摘要</th>
                                <th>总数量</th>
                                <th>总金额</th>
                                <th>状态</th>
                                <th>说明</th>
                                <th>下单人</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var row in Model.List)
                            {
                                <tr class=@rowStyle>
                                    <td>@row.ProductOrderNo</td>
                                    <td>@row.ProductPutOrderDate</td>
                                    <td>@row.Content</td>
                                    <td>@row.SumNum</td>
                                    <td>@row.SumPrice</td>
                                    <td>@row.Status</td>
                                    <td>@row.Remark</td>
                                    <td>@row.Oper</td>
                                    <td>
                                        <div class="tpl-table-black-operation">
                                            <a href=@Url.Action("PutDetail",  new { ProductOrderNo = row.ProductOrderNo })>
                                                <i class="am-icon-pencil"></i> 详情
                                            </a>
                                            <a data-role="Edit" href=@Url.Action("OutEidt", new { ProductOrderNo = row.ProductOrderNo }) class="tpl-table-black-operation-del">
                                                <i class="am-icon-trash"></i> 编辑
                                            </a>
                                            <a data-role="Delete" href=@Url.Action("OutOrderDel", new { id=row.ID}) class="tpl-table-black-operation-del">
                                                <i class="am-icon-trash"></i> 删除
                                            </a>
                                            <a data-role="Approve" href=@Url.Action("OutOrderApprove", new { id=row.ID}) class="tpl-table-black-operation-del">
                                                <i class="am-icon-trash"></i> 审批
                                            </a>
                                            <a data-role="Reject" href=@Url.Action("OutOrderReject", new { id=row.ID}) class="tpl-table-black-operation-del">
                                                <i class="am-icon-trash"></i> 驳回
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                rowStyle = "even gradeC";
                            }
                        </tbody>
                    </table>
                </div>
                <div class="am-u-lg-12 am-cf">
                    <div class="am-fr">
                        <ul class="am-pagination tpl-pagination">
                            <li>
                                <a href=@Url.Action(viewName, new { p = 1,searchFild=ViewBag.searchFild })>«</a>
                            </li>
                            @for (int i = Model.Index - 4; i < Model.Index; i++)
                            {
                                if (i > 0)
                                {
                                    <li><a href=@Url.Action(viewName, new { p = i,searchFild=ViewBag.searchFild  })>@i</a></li>
                                }
                            }
                            <li class="am-active"><a href="#">@Model.Index</a></li>
                            @for (int i = 1; i <= 5; i++)
                            {
                                if (Model.Index + i <= Math.Ceiling((decimal)Model.Count / Model.PageSize))
                                {
                                    <li><a href=@Url.Action(viewName, new { p = Model.Index + i,searchFild=ViewBag.searchFild  })>@(@Model.Index + @i)</a></li>
                                }
                            }
                            <li>
                                <a href=@Url.Action(viewName, new { p = Math.Ceiling((decimal)Model.Count / Model.PageSize),searchFild=ViewBag.searchFild  })>»</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
      $(function(){
          if("@TempData["Msg"]"!="")
              layer.msg("@TempData["Msg"]");
       });
</script>
<script src="~/scripts/amazeui.datatables.min.js"></script>

@section scripts{

    function Search(){

    var value = $("#txt_search").val();

    location.href='@Url.Action("Index")'+'?searchFild='+value;

    }

}